name: 'CI-CD @gear-js/api'

on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: NPM install&build
        run: |
          npm install
          npm run build
        working-directory: api

      - name: Set package registry
        working-directory: api/lib
        run: |
          npm config set registry https://npm.pkg.github.com
          npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm publish --access=public
